//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ThucPhamSach_NVT_.Module.BusinessObjects.ORMDataModel1
{

    public partial class DonHang : XPObject
    {
        string fMaDH;
        public string MaDH
        {
            get { return fMaDH; }
            set { SetPropertyValue<string>(nameof(MaDH), ref fMaDH, value); }
        }
        string fNgayDatHang;
        public string NgayDatHang
        {
            get { return fNgayDatHang; }
            set { SetPropertyValue<string>(nameof(NgayDatHang), ref fNgayDatHang, value); }
        }
        string fNgayGHDuKien;
        public string NgayGHDuKien
        {
            get { return fNgayGHDuKien; }
            set { SetPropertyValue<string>(nameof(NgayGHDuKien), ref fNgayGHDuKien, value); }
        }
        string fTrangThai;
        public string TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<string>(nameof(TrangThai), ref fTrangThai, value); }
        }
        NguoiDung fMaNgD;
        [Association(@"DonHangReferencesNguoiDung")]
        public NguoiDung MaNgD
        {
            get { return fMaNgD; }
            set { SetPropertyValue<NguoiDung>(nameof(MaNgD), ref fMaNgD, value); }
        }
        KhuyenMai fMaKhuyenMai;
        [Association(@"DonHangReferencesKhuyenMai")]
        public KhuyenMai MaKhuyenMai
        {
            get { return fMaKhuyenMai; }
            set { SetPropertyValue<KhuyenMai>(nameof(MaKhuyenMai), ref fMaKhuyenMai, value); }
        }
        [Association(@"ChiTietDonHangReferencesDonHang")]
        public XPCollection<ChiTietDonHang> ChiTietDonHangs { get { return GetCollection<ChiTietDonHang>(nameof(ChiTietDonHangs)); } }
    }

}
