//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ThucPhamSach_NVT_.Module.BusinessObjects.ORMDataModel1
{

    public partial class KhuyenMai : XPObject
    {
        string fMaKM;
        public string MaKM
        {
            get { return fMaKM; }
            set { SetPropertyValue<string>(nameof(MaKM), ref fMaKM, value); }
        }
        string fMoTa;
        public string MoTa
        {
            get { return fMoTa; }
            set { SetPropertyValue<string>(nameof(MoTa), ref fMoTa, value); }
        }
        string fMucKhuyenMai;
        public string MucKhuyenMai
        {
            get { return fMucKhuyenMai; }
            set { SetPropertyValue<string>(nameof(MucKhuyenMai), ref fMucKhuyenMai, value); }
        }
        string fDkKhuyenMai;
        public string DkKhuyenMai
        {
            get { return fDkKhuyenMai; }
            set { SetPropertyValue<string>(nameof(DkKhuyenMai), ref fDkKhuyenMai, value); }
        }
        string fNgayBD;
        public string NgayBD
        {
            get { return fNgayBD; }
            set { SetPropertyValue<string>(nameof(NgayBD), ref fNgayBD, value); }
        }
        string fNgayKT;
        public string NgayKT
        {
            get { return fNgayKT; }
            set { SetPropertyValue<string>(nameof(NgayKT), ref fNgayKT, value); }
        }
        [Association(@"DonHangReferencesKhuyenMai")]
        public XPCollection<DonHang> DonHangs { get { return GetCollection<DonHang>(nameof(DonHangs)); } }
    }

}
