//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ThucPhamSach_NVT_.Module.BusinessObjects.ORMDataModel1
{

    public partial class NhaCC : XPObject
    {
        string fMaNCC;
        public string MaNCC
        {
            get { return fMaNCC; }
            set { SetPropertyValue<string>(nameof(MaNCC), ref fMaNCC, value); }
        }
        string fTenNCC;
        public string TenNCC
        {
            get { return fTenNCC; }
            set { SetPropertyValue<string>(nameof(TenNCC), ref fTenNCC, value); }
        }
        string fDiaChiNCC;
        public string DiaChiNCC
        {
            get { return fDiaChiNCC; }
            set { SetPropertyValue<string>(nameof(DiaChiNCC), ref fDiaChiNCC, value); }
        }
        string fSDTNCC;
        public string SDTNCC
        {
            get { return fSDTNCC; }
            set { SetPropertyValue<string>(nameof(SDTNCC), ref fSDTNCC, value); }
        }
        string fEmailNCC;
        public string EmailNCC
        {
            get { return fEmailNCC; }
            set { SetPropertyValue<string>(nameof(EmailNCC), ref fEmailNCC, value); }
        }
        string fMaXacThuc;
        public string MaXacThuc
        {
            get { return fMaXacThuc; }
            set { SetPropertyValue<string>(nameof(MaXacThuc), ref fMaXacThuc, value); }
        }
        string fNgayXacThuc;
        public string NgayXacThuc
        {
            get { return fNgayXacThuc; }
            set { SetPropertyValue<string>(nameof(NgayXacThuc), ref fNgayXacThuc, value); }
        }
        string fNguocXacThuc;
        public string NguocXacThuc
        {
            get { return fNguocXacThuc; }
            set { SetPropertyValue<string>(nameof(NguocXacThuc), ref fNguocXacThuc, value); }
        }
        string fNDXacThuc;
        public string NDXacThuc
        {
            get { return fNDXacThuc; }
            set { SetPropertyValue<string>(nameof(NDXacThuc), ref fNDXacThuc, value); }
        }
        string fKetQuaXacThuc;
        public string KetQuaXacThuc
        {
            get { return fKetQuaXacThuc; }
            set { SetPropertyValue<string>(nameof(KetQuaXacThuc), ref fKetQuaXacThuc, value); }
        }
        [Association(@"SanPhamReferencesNhaCC")]
        public XPCollection<SanPham> SanPhams { get { return GetCollection<SanPham>(nameof(SanPhams)); } }
    }

}
