//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ThucPhamSach_NVT_.Module.BusinessObjects.ORMDataModel1
{

    public partial class SanPham : XPObject
    {
        string fMaSP;
        public string MaSP
        {
            get { return fMaSP; }
            set { SetPropertyValue<string>(nameof(MaSP), ref fMaSP, value); }
        }
        string fTenSP;
        public string TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<string>(nameof(TenSP), ref fTenSP, value); }
        }
        string fMoTa;
        public string MoTa
        {
            get { return fMoTa; }
            set { SetPropertyValue<string>(nameof(MoTa), ref fMoTa, value); }
        }
        string fGia;
        public string Gia
        {
            get { return fGia; }
            set { SetPropertyValue<string>(nameof(Gia), ref fGia, value); }
        }
        string fHinhAnh;
        public string HinhAnh
        {
            get { return fHinhAnh; }
            set { SetPropertyValue<string>(nameof(HinhAnh), ref fHinhAnh, value); }
        }
        DanhMuc fMaDanhMuc;
        [Association(@"SanPhamReferencesDanhMuc")]
        public DanhMuc MaDanhMuc
        {
            get { return fMaDanhMuc; }
            set { SetPropertyValue<DanhMuc>(nameof(MaDanhMuc), ref fMaDanhMuc, value); }
        }
        NhaCC fMaNCC;
        [Association(@"SanPhamReferencesNhaCC")]
        public NhaCC MaNCC
        {
            get { return fMaNCC; }
            set { SetPropertyValue<NhaCC>(nameof(MaNCC), ref fMaNCC, value); }
        }
        [Association(@"DanhGiaReferencesSanPham")]
        public XPCollection<DanhGia> DanhGias { get { return GetCollection<DanhGia>(nameof(DanhGias)); } }
    }

}
